service: ./737maxcheck
frameworkVersion: '=1.47.0'

provider:
  name: aws
  runtime: nodejs8.10

# Lambda function definitions. Each function defines itself in a separate YAML
# file that resides alongside the function implementation. Unfortunately we have
# to duplicate the function name here due to the way Serverless YAML importing
# and parsing works (in an ideal world we could include these in a list as we do
# for resources).
functions:
  is737Max: ${file(src/functions/is737Max/index.yml):is737Max}

# Custom AWS resource definitions. This includes anything that the Serverless
# framework doesn't handle for us, such as database setup, and overrides of
# Serverless defaults.
resources:
  - ${file(src/resources/apigateway.yml)}
  - ${file(src/resources/iam.yml)}

custom:
  webpack:
    includeModules: true

# Serverless plugins. The "stage-variables" plugin is required to allow us to
# customise the API Gateway stage that gets created automatically by Serverless.
plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-iam-roles-per-function
  - serverless-plugin-stage-variables
